# Generated by Django 5.2.12 on 2026-03-14 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ride",
            fields=[
                ("id_ride", models.AutoField(primary_key=True, serialize=False)),
                ("status", models.CharField(max_length=255)),
                ("pickup_latitude", models.FloatField()),
                ("pickup_longitude", models.FloatField()),
                ("dropoff_latitude", models.FloatField()),
                ("dropoff_longitude", models.FloatField()),
                ("pickup_time", models.DateTimeField()),
                (
                    "id_driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rides_as_driver",
                        to="users.user",
                    ),
                ),
                (
                    "id_rider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rides_as_rider",
                        to="users.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RideEvent",
            fields=[
                ("id_ride_event", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField()),
                (
                    "id_ride",
                    models.ForeignKey(
                        db_column="id_ride",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="rides.ride",
                    ),
                ),
            ],
        ),
    ]
