# Generated by Django 5.2.12 on 2026-03-15 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0001_initial"),
        ("users", "0002_alter_user_email_alter_user_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ride",
            name="id_driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rides_as_driver",
                to="users.user",
            ),
        ),
        migrations.AlterField(
            model_name="ride",
            name="id_rider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rides_as_rider",
                to="users.user",
            ),
        ),
        migrations.AlterField(
            model_name="ride",
            name="pickup_time",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="ride",
            name="status",
            field=models.CharField(
                choices=[
                    ("requested", "Requested"),
                    ("accepted", "Accepted"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="rideevent",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
