# Generated by Django 5.2.12 on 2026-03-15 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0002_alter_ride_id_driver_alter_ride_id_rider_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ride",
            name="status",
            field=models.CharField(
                choices=[
                    ("en-route", "En Route"),
                    ("pickup", "Pickup"),
                    ("dropoff", "Dropoff"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
